/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompanyUpdatePostedOn from './CompanyUpdatePostedOn';

/**
 * The AccomplishmentOrg model module.
 * @module model/AccomplishmentOrg
 * @version 1.0.0
 */
class AccomplishmentOrg {
    /**
     * Constructs a new <code>AccomplishmentOrg</code>.
     * @alias module:model/AccomplishmentOrg
     */
    constructor() { 
        
        AccomplishmentOrg.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccomplishmentOrg</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccomplishmentOrg} obj Optional instance to populate.
     * @return {module:model/AccomplishmentOrg} The populated <code>AccomplishmentOrg</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccomplishmentOrg();

            if (data.hasOwnProperty('starts_at')) {
                obj['starts_at'] = CompanyUpdatePostedOn.constructFromObject(data['starts_at']);
            }
            if (data.hasOwnProperty('ends_at')) {
                obj['ends_at'] = CompanyUpdatePostedOn.constructFromObject(data['ends_at']);
            }
            if (data.hasOwnProperty('org_name')) {
                obj['org_name'] = ApiClient.convertToType(data['org_name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AccomplishmentOrg</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AccomplishmentOrg</code>.
     */
    static validateJSON(data) {
        // validate the optional field `starts_at`
        if (data['starts_at']) { // data not null
          CompanyUpdatePostedOn.validateJSON(data['starts_at']);
        }
        // validate the optional field `ends_at`
        if (data['ends_at']) { // data not null
          CompanyUpdatePostedOn.validateJSON(data['ends_at']);
        }
        // ensure the json data is a string
        if (data['org_name'] && !(typeof data['org_name'] === 'string' || data['org_name'] instanceof String)) {
            throw new Error("Expected the field `org_name` to be a primitive type in the JSON string but got " + data['org_name']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {module:model/CompanyUpdatePostedOn} starts_at
 */
AccomplishmentOrg.prototype['starts_at'] = undefined;

/**
 * @member {module:model/CompanyUpdatePostedOn} ends_at
 */
AccomplishmentOrg.prototype['ends_at'] = undefined;

/**
 * @member {String} org_name
 */
AccomplishmentOrg.prototype['org_name'] = undefined;

/**
 * @member {String} title
 */
AccomplishmentOrg.prototype['title'] = undefined;

/**
 * @member {String} description
 */
AccomplishmentOrg.prototype['description'] = undefined;






export default AccomplishmentOrg;

