/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompanyLocation model module.
 * @module model/CompanyLocation
 * @version 1.0.0
 */
class CompanyLocation {
    /**
     * Constructs a new <code>CompanyLocation</code>.
     * @alias module:model/CompanyLocation
     */
    constructor() { 
        
        CompanyLocation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompanyLocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanyLocation} obj Optional instance to populate.
     * @return {module:model/CompanyLocation} The populated <code>CompanyLocation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyLocation();

            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
            if (data.hasOwnProperty('line_1')) {
                obj['line_1'] = ApiClient.convertToType(data['line_1'], 'String');
            }
            if (data.hasOwnProperty('is_hq')) {
                obj['is_hq'] = ApiClient.convertToType(data['is_hq'], 'Boolean');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompanyLocation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompanyLocation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['postal_code'] && !(typeof data['postal_code'] === 'string' || data['postal_code'] instanceof String)) {
            throw new Error("Expected the field `postal_code` to be a primitive type in the JSON string but got " + data['postal_code']);
        }
        // ensure the json data is a string
        if (data['line_1'] && !(typeof data['line_1'] === 'string' || data['line_1'] instanceof String)) {
            throw new Error("Expected the field `line_1` to be a primitive type in the JSON string but got " + data['line_1']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }

        return true;
    }


}



/**
 * @member {String} country
 */
CompanyLocation.prototype['country'] = undefined;

/**
 * @member {String} city
 */
CompanyLocation.prototype['city'] = undefined;

/**
 * @member {String} postal_code
 */
CompanyLocation.prototype['postal_code'] = undefined;

/**
 * @member {String} line_1
 */
CompanyLocation.prototype['line_1'] = undefined;

/**
 * @member {Boolean} is_hq
 */
CompanyLocation.prototype['is_hq'] = undefined;

/**
 * @member {String} state
 */
CompanyLocation.prototype['state'] = undefined;






export default CompanyLocation;

