/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreditBalance model module.
 * @module model/CreditBalance
 * @version 1.0.0
 */
class CreditBalance {
    /**
     * Constructs a new <code>CreditBalance</code>.
     * @alias module:model/CreditBalance
     */
    constructor() { 
        
        CreditBalance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditBalance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditBalance} obj Optional instance to populate.
     * @return {module:model/CreditBalance} The populated <code>CreditBalance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditBalance();

            if (data.hasOwnProperty('credit_balance')) {
                obj['credit_balance'] = ApiClient.convertToType(data['credit_balance'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreditBalance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreditBalance</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Your current credit(s)
 * @member {Number} credit_balance
 */
CreditBalance.prototype['credit_balance'] = undefined;






export default CreditBalance;

