/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DisposableEmail model module.
 * @module model/DisposableEmail
 * @version 1.0.0
 */
class DisposableEmail {
    /**
     * Constructs a new <code>DisposableEmail</code>.
     * @alias module:model/DisposableEmail
     */
    constructor() { 
        
        DisposableEmail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DisposableEmail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DisposableEmail} obj Optional instance to populate.
     * @return {module:model/DisposableEmail} The populated <code>DisposableEmail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DisposableEmail();

            if (data.hasOwnProperty('is_disposable_email')) {
                obj['is_disposable_email'] = ApiClient.convertToType(data['is_disposable_email'], 'Boolean');
            }
            if (data.hasOwnProperty('is_free_email')) {
                obj['is_free_email'] = ApiClient.convertToType(data['is_free_email'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DisposableEmail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DisposableEmail</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Returns a boolean value of the disposable nature of the given email address
 * @member {Boolean} is_disposable_email
 */
DisposableEmail.prototype['is_disposable_email'] = undefined;

/**
 * Returns a boolean value of the free status of the given email address
 * @member {Boolean} is_free_email
 */
DisposableEmail.prototype['is_free_email'] = undefined;






export default DisposableEmail;

