/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Employee from './Employee';

/**
 * The EmployeeList model module.
 * @module model/EmployeeList
 * @version 1.0.0
 */
class EmployeeList {
    /**
     * Constructs a new <code>EmployeeList</code>.
     * @alias module:model/EmployeeList
     */
    constructor() { 
        
        EmployeeList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmployeeList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmployeeList} obj Optional instance to populate.
     * @return {module:model/EmployeeList} The populated <code>EmployeeList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmployeeList();

            if (data.hasOwnProperty('employees')) {
                obj['employees'] = ApiClient.convertToType(data['employees'], [Employee]);
            }
            if (data.hasOwnProperty('next_page')) {
                obj['next_page'] = ApiClient.convertToType(data['next_page'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmployeeList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmployeeList</code>.
     */
    static validateJSON(data) {
        if (data['employees']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['employees'])) {
                throw new Error("Expected the field `employees` to be an array in the JSON data but got " + data['employees']);
            }
            // validate the optional field `employees` (array)
            for (const item of data['employees']) {
                Employee.validateJsonObject(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page'] && !(typeof data['next_page'] === 'string' || data['next_page'] instanceof String)) {
            throw new Error("Expected the field `next_page` to be a primitive type in the JSON string but got " + data['next_page']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Employee>} employees
 */
EmployeeList.prototype['employees'] = undefined;

/**
 * @member {String} next_page
 */
EmployeeList.prototype['next_page'] = undefined;






export default EmployeeList;

