/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmployeeCount model module.
 * @module model/EmployeeCount
 * @version 1.0.0
 */
class EmployeeCount {
    /**
     * Constructs a new <code>EmployeeCount</code>.
     * @alias module:model/EmployeeCount
     */
    constructor() { 
        
        EmployeeCount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmployeeCount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmployeeCount} obj Optional instance to populate.
     * @return {module:model/EmployeeCount} The populated <code>EmployeeCount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmployeeCount();

            if (data.hasOwnProperty('total_employee')) {
                obj['total_employee'] = ApiClient.convertToType(data['total_employee'], 'Number');
            }
            if (data.hasOwnProperty('linkedin_employee_count')) {
                obj['linkedin_employee_count'] = ApiClient.convertToType(data['linkedin_employee_count'], 'Number');
            }
            if (data.hasOwnProperty('linkdb_employee_count')) {
                obj['linkdb_employee_count'] = ApiClient.convertToType(data['linkdb_employee_count'], 'Number');
            }
            if (data.hasOwnProperty('regression_notice')) {
                obj['regression_notice'] = ApiClient.convertToType(data['regression_notice'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmployeeCount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmployeeCount</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['regression_notice'] && !(typeof data['regression_notice'] === 'string' || data['regression_notice'] instanceof String)) {
            throw new Error("Expected the field `regression_notice` to be a primitive type in the JSON string but got " + data['regression_notice']);
        }

        return true;
    }


}



/**
 * @member {Number} total_employee
 */
EmployeeCount.prototype['total_employee'] = undefined;

/**
 * The scraped value of employee count of this company from it's LinkedIn profile. This value does not respect `employement_status` parameter. It will always return the curent employee count of this company from LinkedIn.
 * @member {Number} linkedin_employee_count
 */
EmployeeCount.prototype['linkedin_employee_count'] = undefined;

/**
 * The total number of employees found in LinkDB for this company. This value is limited by pre-crawled LinkedIn profiles stored in [LinkDB](https://nubela.co/proxycurl/linkdb)
 * @member {Number} linkdb_employee_count
 */
EmployeeCount.prototype['linkdb_employee_count'] = undefined;

/**
 * @member {String} regression_notice
 * @default 'Hello developer, we have renamed `total_employee` key to `linkdb_employee_count` to fix the bad grammar. We have kept `total_employee` for backwards compatibility, so please do not use it as we will remove it down the road. To see which keys are officially supported, refer to our API docs at https://nubela.co/proxycurl/docs#company-api-employee-count-endpoint'
 */
EmployeeCount.prototype['regression_notice'] = 'Hello developer, we have renamed `total_employee` key to `linkdb_employee_count` to fix the bad grammar. We have kept `total_employee` for backwards compatibility, so please do not use it as we will remove it down the road. To see which keys are officially supported, refer to our API docs at https://nubela.co/proxycurl/docs#company-api-employee-count-endpoint';






export default EmployeeCount;

