/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Job from './Job';

/**
 * The JobListPage model module.
 * @module model/JobListPage
 * @version 1.0.0
 */
class JobListPage {
    /**
     * Constructs a new <code>JobListPage</code>.
     * @alias module:model/JobListPage
     */
    constructor() { 
        
        JobListPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobListPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobListPage} obj Optional instance to populate.
     * @return {module:model/JobListPage} The populated <code>JobListPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobListPage();

            if (data.hasOwnProperty('job')) {
                obj['job'] = ApiClient.convertToType(data['job'], [Job]);
            }
            if (data.hasOwnProperty('next_page_no')) {
                obj['next_page_no'] = ApiClient.convertToType(data['next_page_no'], 'Number');
            }
            if (data.hasOwnProperty('next_page_api_url')) {
                obj['next_page_api_url'] = ApiClient.convertToType(data['next_page_api_url'], 'String');
            }
            if (data.hasOwnProperty('previous_page_no')) {
                obj['previous_page_no'] = ApiClient.convertToType(data['previous_page_no'], 'Number');
            }
            if (data.hasOwnProperty('previous_page_api_url')) {
                obj['previous_page_api_url'] = ApiClient.convertToType(data['previous_page_api_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobListPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobListPage</code>.
     */
    static validateJSON(data) {
        if (data['job']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['job'])) {
                throw new Error("Expected the field `job` to be an array in the JSON data but got " + data['job']);
            }
            // validate the optional field `job` (array)
            for (const item of data['job']) {
                Job.validateJsonObject(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page_api_url'] && !(typeof data['next_page_api_url'] === 'string' || data['next_page_api_url'] instanceof String)) {
            throw new Error("Expected the field `next_page_api_url` to be a primitive type in the JSON string but got " + data['next_page_api_url']);
        }
        // ensure the json data is a string
        if (data['previous_page_api_url'] && !(typeof data['previous_page_api_url'] === 'string' || data['previous_page_api_url'] instanceof String)) {
            throw new Error("Expected the field `previous_page_api_url` to be a primitive type in the JSON string but got " + data['previous_page_api_url']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Job>} job
 */
JobListPage.prototype['job'] = undefined;

/**
 * @member {Number} next_page_no
 */
JobListPage.prototype['next_page_no'] = undefined;

/**
 * @member {String} next_page_api_url
 */
JobListPage.prototype['next_page_api_url'] = undefined;

/**
 * @member {Number} previous_page_no
 */
JobListPage.prototype['previous_page_no'] = undefined;

/**
 * @member {String} previous_page_api_url
 */
JobListPage.prototype['previous_page_api_url'] = undefined;






export default JobListPage;

