/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobCompany from './JobCompany';

/**
 * The LinkedinJobCompany model module.
 * @module model/LinkedinJobCompany
 * @version 1.0.0
 */
class LinkedinJobCompany {
    /**
     * Constructs a new <code>LinkedinJobCompany</code>.
     * @alias module:model/LinkedinJobCompany
     * @implements module:model/JobCompany
     */
    constructor() { 
        JobCompany.initialize(this);
        LinkedinJobCompany.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LinkedinJobCompany</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LinkedinJobCompany} obj Optional instance to populate.
     * @return {module:model/LinkedinJobCompany} The populated <code>LinkedinJobCompany</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LinkedinJobCompany();
            JobCompany.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LinkedinJobCompany</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LinkedinJobCompany</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['logo'] && !(typeof data['logo'] === 'string' || data['logo'] instanceof String)) {
            throw new Error("Expected the field `logo` to be a primitive type in the JSON string but got " + data['logo']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
LinkedinJobCompany.prototype['name'] = undefined;

/**
 * @member {String} url
 */
LinkedinJobCompany.prototype['url'] = undefined;

/**
 * @member {String} logo
 */
LinkedinJobCompany.prototype['logo'] = undefined;


// Implement JobCompany interface:
/**
 * @member {String} name
 */
JobCompany.prototype['name'] = undefined;
/**
 * @member {String} url
 */
JobCompany.prototype['url'] = undefined;
/**
 * @member {String} logo
 */
JobCompany.prototype['logo'] = undefined;




export default LinkedinJobCompany;

