/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PDLEmailResult model module.
 * @module model/PDLEmailResult
 * @version 1.0.0
 */
class PDLEmailResult {
    /**
     * Constructs a new <code>PDLEmailResult</code>.
     * @alias module:model/PDLEmailResult
     */
    constructor() { 
        
        PDLEmailResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PDLEmailResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PDLEmailResult} obj Optional instance to populate.
     * @return {module:model/PDLEmailResult} The populated <code>PDLEmailResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PDLEmailResult();

            if (data.hasOwnProperty('emails')) {
                obj['emails'] = ApiClient.convertToType(data['emails'], ['String']);
            }
            if (data.hasOwnProperty('invalid_emails')) {
                obj['invalid_emails'] = ApiClient.convertToType(data['invalid_emails'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PDLEmailResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PDLEmailResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['emails'])) {
            throw new Error("Expected the field `emails` to be an array in the JSON data but got " + data['emails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['invalid_emails'])) {
            throw new Error("Expected the field `invalid_emails` to be an array in the JSON data but got " + data['invalid_emails']);
        }

        return true;
    }


}



/**
 * A list of personal emails
 * @member {Array.<String>} emails
 */
PDLEmailResult.prototype['emails'] = undefined;

/**
 * A list of invalid personal emails
 * @member {Array.<String>} invalid_emails
 */
PDLEmailResult.prototype['invalid_emails'] = undefined;






export default PDLEmailResult;

