/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PDLPhoneNumberResult model module.
 * @module model/PDLPhoneNumberResult
 * @version 1.0.0
 */
class PDLPhoneNumberResult {
    /**
     * Constructs a new <code>PDLPhoneNumberResult</code>.
     * @alias module:model/PDLPhoneNumberResult
     */
    constructor() { 
        
        PDLPhoneNumberResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PDLPhoneNumberResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PDLPhoneNumberResult} obj Optional instance to populate.
     * @return {module:model/PDLPhoneNumberResult} The populated <code>PDLPhoneNumberResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PDLPhoneNumberResult();

            if (data.hasOwnProperty('numbers')) {
                obj['numbers'] = ApiClient.convertToType(data['numbers'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PDLPhoneNumberResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PDLPhoneNumberResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['numbers'])) {
            throw new Error("Expected the field `numbers` to be an array in the JSON data but got " + data['numbers']);
        }

        return true;
    }


}



/**
 * A list of contact numbers
 * @member {Array.<String>} numbers
 */
PDLPhoneNumberResult.prototype['numbers'] = undefined;






export default PDLPhoneNumberResult;

