/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccomplishmentOrg from './AccomplishmentOrg';
import Activity from './Activity';
import Article from './Article';
import Certification from './Certification';
import Course from './Course';
import Education from './Education';
import Experience from './Experience';
import HonourAward from './HonourAward';
import Patent from './Patent';
import PeopleAlsoViewed from './PeopleAlsoViewed';
import PersonEndpointResponseBirthDate from './PersonEndpointResponseBirthDate';
import PersonEndpointResponseExtra from './PersonEndpointResponseExtra';
import PersonEndpointResponseInferredSalary from './PersonEndpointResponseInferredSalary';
import PersonGroup from './PersonGroup';
import Project from './Project';
import Publication from './Publication';
import SimilarProfile from './SimilarProfile';
import TestScore from './TestScore';
import VolunteeringExperience from './VolunteeringExperience';

/**
 * The PersonEndpointResponse model module.
 * @module model/PersonEndpointResponse
 * @version 1.0.0
 */
class PersonEndpointResponse {
    /**
     * Constructs a new <code>PersonEndpointResponse</code>.
     * @alias module:model/PersonEndpointResponse
     */
    constructor() { 
        
        PersonEndpointResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonEndpointResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonEndpointResponse} obj Optional instance to populate.
     * @return {module:model/PersonEndpointResponse} The populated <code>PersonEndpointResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonEndpointResponse();

            if (data.hasOwnProperty('public_identifier')) {
                obj['public_identifier'] = ApiClient.convertToType(data['public_identifier'], 'String');
            }
            if (data.hasOwnProperty('profile_pic_url')) {
                obj['profile_pic_url'] = ApiClient.convertToType(data['profile_pic_url'], 'String');
            }
            if (data.hasOwnProperty('background_cover_image_url')) {
                obj['background_cover_image_url'] = ApiClient.convertToType(data['background_cover_image_url'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('full_name')) {
                obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
            }
            if (data.hasOwnProperty('occupation')) {
                obj['occupation'] = ApiClient.convertToType(data['occupation'], 'String');
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('country_full_name')) {
                obj['country_full_name'] = ApiClient.convertToType(data['country_full_name'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('experiences')) {
                obj['experiences'] = ApiClient.convertToType(data['experiences'], [Experience]);
            }
            if (data.hasOwnProperty('education')) {
                obj['education'] = ApiClient.convertToType(data['education'], [Education]);
            }
            if (data.hasOwnProperty('languages')) {
                obj['languages'] = ApiClient.convertToType(data['languages'], ['String']);
            }
            if (data.hasOwnProperty('accomplishment_organisations')) {
                obj['accomplishment_organisations'] = ApiClient.convertToType(data['accomplishment_organisations'], [AccomplishmentOrg]);
            }
            if (data.hasOwnProperty('accomplishment_publications')) {
                obj['accomplishment_publications'] = ApiClient.convertToType(data['accomplishment_publications'], [Publication]);
            }
            if (data.hasOwnProperty('accomplishment_honors_awards')) {
                obj['accomplishment_honors_awards'] = ApiClient.convertToType(data['accomplishment_honors_awards'], [HonourAward]);
            }
            if (data.hasOwnProperty('accomplishment_patents')) {
                obj['accomplishment_patents'] = ApiClient.convertToType(data['accomplishment_patents'], [Patent]);
            }
            if (data.hasOwnProperty('accomplishment_courses')) {
                obj['accomplishment_courses'] = ApiClient.convertToType(data['accomplishment_courses'], [Course]);
            }
            if (data.hasOwnProperty('accomplishment_projects')) {
                obj['accomplishment_projects'] = ApiClient.convertToType(data['accomplishment_projects'], [Project]);
            }
            if (data.hasOwnProperty('accomplishment_test_scores')) {
                obj['accomplishment_test_scores'] = ApiClient.convertToType(data['accomplishment_test_scores'], [TestScore]);
            }
            if (data.hasOwnProperty('volunteer_work')) {
                obj['volunteer_work'] = ApiClient.convertToType(data['volunteer_work'], [VolunteeringExperience]);
            }
            if (data.hasOwnProperty('certifications')) {
                obj['certifications'] = ApiClient.convertToType(data['certifications'], [Certification]);
            }
            if (data.hasOwnProperty('connections')) {
                obj['connections'] = ApiClient.convertToType(data['connections'], 'Number');
            }
            if (data.hasOwnProperty('people_also_viewed')) {
                obj['people_also_viewed'] = ApiClient.convertToType(data['people_also_viewed'], [PeopleAlsoViewed]);
            }
            if (data.hasOwnProperty('recommendations')) {
                obj['recommendations'] = ApiClient.convertToType(data['recommendations'], ['String']);
            }
            if (data.hasOwnProperty('activities')) {
                obj['activities'] = ApiClient.convertToType(data['activities'], [Activity]);
            }
            if (data.hasOwnProperty('similarly_named_profiles')) {
                obj['similarly_named_profiles'] = ApiClient.convertToType(data['similarly_named_profiles'], [SimilarProfile]);
            }
            if (data.hasOwnProperty('articles')) {
                obj['articles'] = ApiClient.convertToType(data['articles'], [Article]);
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [PersonGroup]);
            }
            if (data.hasOwnProperty('skills')) {
                obj['skills'] = ApiClient.convertToType(data['skills'], ['String']);
            }
            if (data.hasOwnProperty('inferred_salary')) {
                obj['inferred_salary'] = PersonEndpointResponseInferredSalary.constructFromObject(data['inferred_salary']);
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('birth_date')) {
                obj['birth_date'] = PersonEndpointResponseBirthDate.constructFromObject(data['birth_date']);
            }
            if (data.hasOwnProperty('industry')) {
                obj['industry'] = ApiClient.convertToType(data['industry'], 'String');
            }
            if (data.hasOwnProperty('interests')) {
                obj['interests'] = ApiClient.convertToType(data['interests'], ['String']);
            }
            if (data.hasOwnProperty('extra')) {
                obj['extra'] = PersonEndpointResponseExtra.constructFromObject(data['extra']);
            }
            if (data.hasOwnProperty('personal_emails')) {
                obj['personal_emails'] = ApiClient.convertToType(data['personal_emails'], ['String']);
            }
            if (data.hasOwnProperty('personal_numbers')) {
                obj['personal_numbers'] = ApiClient.convertToType(data['personal_numbers'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonEndpointResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonEndpointResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['public_identifier'] && !(typeof data['public_identifier'] === 'string' || data['public_identifier'] instanceof String)) {
            throw new Error("Expected the field `public_identifier` to be a primitive type in the JSON string but got " + data['public_identifier']);
        }
        // ensure the json data is a string
        if (data['profile_pic_url'] && !(typeof data['profile_pic_url'] === 'string' || data['profile_pic_url'] instanceof String)) {
            throw new Error("Expected the field `profile_pic_url` to be a primitive type in the JSON string but got " + data['profile_pic_url']);
        }
        // ensure the json data is a string
        if (data['background_cover_image_url'] && !(typeof data['background_cover_image_url'] === 'string' || data['background_cover_image_url'] instanceof String)) {
            throw new Error("Expected the field `background_cover_image_url` to be a primitive type in the JSON string but got " + data['background_cover_image_url']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['full_name'] && !(typeof data['full_name'] === 'string' || data['full_name'] instanceof String)) {
            throw new Error("Expected the field `full_name` to be a primitive type in the JSON string but got " + data['full_name']);
        }
        // ensure the json data is a string
        if (data['occupation'] && !(typeof data['occupation'] === 'string' || data['occupation'] instanceof String)) {
            throw new Error("Expected the field `occupation` to be a primitive type in the JSON string but got " + data['occupation']);
        }
        // ensure the json data is a string
        if (data['headline'] && !(typeof data['headline'] === 'string' || data['headline'] instanceof String)) {
            throw new Error("Expected the field `headline` to be a primitive type in the JSON string but got " + data['headline']);
        }
        // ensure the json data is a string
        if (data['summary'] && !(typeof data['summary'] === 'string' || data['summary'] instanceof String)) {
            throw new Error("Expected the field `summary` to be a primitive type in the JSON string but got " + data['summary']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['country_full_name'] && !(typeof data['country_full_name'] === 'string' || data['country_full_name'] instanceof String)) {
            throw new Error("Expected the field `country_full_name` to be a primitive type in the JSON string but got " + data['country_full_name']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        if (data['experiences']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['experiences'])) {
                throw new Error("Expected the field `experiences` to be an array in the JSON data but got " + data['experiences']);
            }
            // validate the optional field `experiences` (array)
            for (const item of data['experiences']) {
                Experience.validateJsonObject(item);
            };
        }
        if (data['education']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['education'])) {
                throw new Error("Expected the field `education` to be an array in the JSON data but got " + data['education']);
            }
            // validate the optional field `education` (array)
            for (const item of data['education']) {
                Education.validateJsonObject(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['languages'])) {
            throw new Error("Expected the field `languages` to be an array in the JSON data but got " + data['languages']);
        }
        if (data['accomplishment_organisations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_organisations'])) {
                throw new Error("Expected the field `accomplishment_organisations` to be an array in the JSON data but got " + data['accomplishment_organisations']);
            }
            // validate the optional field `accomplishment_organisations` (array)
            for (const item of data['accomplishment_organisations']) {
                AccomplishmentOrg.validateJsonObject(item);
            };
        }
        if (data['accomplishment_publications']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_publications'])) {
                throw new Error("Expected the field `accomplishment_publications` to be an array in the JSON data but got " + data['accomplishment_publications']);
            }
            // validate the optional field `accomplishment_publications` (array)
            for (const item of data['accomplishment_publications']) {
                Publication.validateJsonObject(item);
            };
        }
        if (data['accomplishment_honors_awards']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_honors_awards'])) {
                throw new Error("Expected the field `accomplishment_honors_awards` to be an array in the JSON data but got " + data['accomplishment_honors_awards']);
            }
            // validate the optional field `accomplishment_honors_awards` (array)
            for (const item of data['accomplishment_honors_awards']) {
                HonourAward.validateJsonObject(item);
            };
        }
        if (data['accomplishment_patents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_patents'])) {
                throw new Error("Expected the field `accomplishment_patents` to be an array in the JSON data but got " + data['accomplishment_patents']);
            }
            // validate the optional field `accomplishment_patents` (array)
            for (const item of data['accomplishment_patents']) {
                Patent.validateJsonObject(item);
            };
        }
        if (data['accomplishment_courses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_courses'])) {
                throw new Error("Expected the field `accomplishment_courses` to be an array in the JSON data but got " + data['accomplishment_courses']);
            }
            // validate the optional field `accomplishment_courses` (array)
            for (const item of data['accomplishment_courses']) {
                Course.validateJsonObject(item);
            };
        }
        if (data['accomplishment_projects']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_projects'])) {
                throw new Error("Expected the field `accomplishment_projects` to be an array in the JSON data but got " + data['accomplishment_projects']);
            }
            // validate the optional field `accomplishment_projects` (array)
            for (const item of data['accomplishment_projects']) {
                Project.validateJsonObject(item);
            };
        }
        if (data['accomplishment_test_scores']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accomplishment_test_scores'])) {
                throw new Error("Expected the field `accomplishment_test_scores` to be an array in the JSON data but got " + data['accomplishment_test_scores']);
            }
            // validate the optional field `accomplishment_test_scores` (array)
            for (const item of data['accomplishment_test_scores']) {
                TestScore.validateJsonObject(item);
            };
        }
        if (data['volunteer_work']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['volunteer_work'])) {
                throw new Error("Expected the field `volunteer_work` to be an array in the JSON data but got " + data['volunteer_work']);
            }
            // validate the optional field `volunteer_work` (array)
            for (const item of data['volunteer_work']) {
                VolunteeringExperience.validateJsonObject(item);
            };
        }
        if (data['certifications']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['certifications'])) {
                throw new Error("Expected the field `certifications` to be an array in the JSON data but got " + data['certifications']);
            }
            // validate the optional field `certifications` (array)
            for (const item of data['certifications']) {
                Certification.validateJsonObject(item);
            };
        }
        if (data['people_also_viewed']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['people_also_viewed'])) {
                throw new Error("Expected the field `people_also_viewed` to be an array in the JSON data but got " + data['people_also_viewed']);
            }
            // validate the optional field `people_also_viewed` (array)
            for (const item of data['people_also_viewed']) {
                PeopleAlsoViewed.validateJsonObject(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['recommendations'])) {
            throw new Error("Expected the field `recommendations` to be an array in the JSON data but got " + data['recommendations']);
        }
        if (data['activities']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['activities'])) {
                throw new Error("Expected the field `activities` to be an array in the JSON data but got " + data['activities']);
            }
            // validate the optional field `activities` (array)
            for (const item of data['activities']) {
                Activity.validateJsonObject(item);
            };
        }
        if (data['similarly_named_profiles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['similarly_named_profiles'])) {
                throw new Error("Expected the field `similarly_named_profiles` to be an array in the JSON data but got " + data['similarly_named_profiles']);
            }
            // validate the optional field `similarly_named_profiles` (array)
            for (const item of data['similarly_named_profiles']) {
                SimilarProfile.validateJsonObject(item);
            };
        }
        if (data['articles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['articles'])) {
                throw new Error("Expected the field `articles` to be an array in the JSON data but got " + data['articles']);
            }
            // validate the optional field `articles` (array)
            for (const item of data['articles']) {
                Article.validateJsonObject(item);
            };
        }
        if (data['groups']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['groups'])) {
                throw new Error("Expected the field `groups` to be an array in the JSON data but got " + data['groups']);
            }
            // validate the optional field `groups` (array)
            for (const item of data['groups']) {
                PersonGroup.validateJsonObject(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['skills'])) {
            throw new Error("Expected the field `skills` to be an array in the JSON data but got " + data['skills']);
        }
        // validate the optional field `inferred_salary`
        if (data['inferred_salary']) { // data not null
          PersonEndpointResponseInferredSalary.validateJSON(data['inferred_salary']);
        }
        // ensure the json data is a string
        if (data['gender'] && !(typeof data['gender'] === 'string' || data['gender'] instanceof String)) {
            throw new Error("Expected the field `gender` to be a primitive type in the JSON string but got " + data['gender']);
        }
        // validate the optional field `birth_date`
        if (data['birth_date']) { // data not null
          PersonEndpointResponseBirthDate.validateJSON(data['birth_date']);
        }
        // ensure the json data is a string
        if (data['industry'] && !(typeof data['industry'] === 'string' || data['industry'] instanceof String)) {
            throw new Error("Expected the field `industry` to be a primitive type in the JSON string but got " + data['industry']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['interests'])) {
            throw new Error("Expected the field `interests` to be an array in the JSON data but got " + data['interests']);
        }
        // validate the optional field `extra`
        if (data['extra']) { // data not null
          PersonEndpointResponseExtra.validateJSON(data['extra']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['personal_emails'])) {
            throw new Error("Expected the field `personal_emails` to be an array in the JSON data but got " + data['personal_emails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['personal_numbers'])) {
            throw new Error("Expected the field `personal_numbers` to be an array in the JSON data but got " + data['personal_numbers']);
        }

        return true;
    }


}



/**
 * The vanity identifier of the public LinkedIn profile. The vanity identifier comes after the `/in/` part of the LinkedIn Profile URL in the following format: `https://www.linkedin.com/in/<public_identifier>`
 * @member {String} public_identifier
 */
PersonEndpointResponse.prototype['public_identifier'] = undefined;

/**
 * A temporary link to the user's profile picture that is valid for 30 minutes. The temporal nature of the link is by design to prevent having Proxycurl be the mirror for the images. The developer is expected to handle these images by downloading the image and re-hosting the image. See [this post](https://nubela.co/blog/why-is-the-api-returning-s3-links-for-profile-pictures-scraped-from-linkedin-profiles/) for context.                                  Some profile pictures might be of the standard LinkedIn's profile picture placeholder. It is so because. See [this post](https://nubela.co/blog/why-do-most-linkedin-profiles-fetched-via-the-person-profile-endpoint-return-a-placeholder-profile-picture/) for context.
 * @member {String} profile_pic_url
 */
PersonEndpointResponse.prototype['profile_pic_url'] = undefined;

/**
 * A temporary link to the user's background cover picture that is valid for 30 minutes. The temporal nature of the link is by design to prevent having Proxycurl be the mirror for the images. The developer is expected to handle these images by downloading the image and re-hosting the image. See [this post](https://nubela.co/blog/why-is-the-api-returning-s3-links-for-profile-pictures-scraped-from-linkedin-profiles/) for context.
 * @member {String} background_cover_image_url
 */
PersonEndpointResponse.prototype['background_cover_image_url'] = undefined;

/**
 * First name of the user.
 * @member {String} first_name
 */
PersonEndpointResponse.prototype['first_name'] = undefined;

/**
 * Last name of the user.
 * @member {String} last_name
 */
PersonEndpointResponse.prototype['last_name'] = undefined;

/**
 * Full name of the user (`first_name` + `last_name`)
 * @member {String} full_name
 */
PersonEndpointResponse.prototype['full_name'] = undefined;

/**
 * The title and company name of the user's current employment.
 * @member {String} occupation
 */
PersonEndpointResponse.prototype['occupation'] = undefined;

/**
 * The tagline written by the user for his profile.
 * @member {String} headline
 */
PersonEndpointResponse.prototype['headline'] = undefined;

/**
 * A blurb (longer than the tagline) written by the user for his profile.
 * @member {String} summary
 */
PersonEndpointResponse.prototype['summary'] = undefined;

/**
 * The user's country of residence depicted by a 2-letter country code (ISO 3166-1 alpha-2).
 * @member {String} country
 */
PersonEndpointResponse.prototype['country'] = undefined;

/**
 * The user's country of residence, in English words.
 * @member {String} country_full_name
 */
PersonEndpointResponse.prototype['country_full_name'] = undefined;

/**
 * The city that the user is living at.
 * @member {String} city
 */
PersonEndpointResponse.prototype['city'] = undefined;

/**
 * The state that the user is living at.
 * @member {String} state
 */
PersonEndpointResponse.prototype['state'] = undefined;

/**
 * The user's list of historic work experiences.
 * @member {Array.<module:model/Experience>} experiences
 */
PersonEndpointResponse.prototype['experiences'] = undefined;

/**
 * The user's list of education background.
 * @member {Array.<module:model/Education>} education
 */
PersonEndpointResponse.prototype['education'] = undefined;

/**
 * A list of languages that the user claims to be familiar with, and has added to his/her profile.                                  Do note that we do not have the proficiency level as that data point is not available on a public LinkedIn profile.
 * @member {Array.<String>} languages
 */
PersonEndpointResponse.prototype['languages'] = undefined;

/**
 * List of noteworthy organizations that this user is part of.
 * @member {Array.<module:model/AccomplishmentOrg>} accomplishment_organisations
 */
PersonEndpointResponse.prototype['accomplishment_organisations'] = undefined;

/**
 * List of noteworthy publications that this user has partook in.
 * @member {Array.<module:model/Publication>} accomplishment_publications
 */
PersonEndpointResponse.prototype['accomplishment_publications'] = undefined;

/**
 * List of noteworthy honours and awards that this user has won.
 * @member {Array.<module:model/HonourAward>} accomplishment_honors_awards
 */
PersonEndpointResponse.prototype['accomplishment_honors_awards'] = undefined;

/**
 * List of noteworthy patents won by this user.
 * @member {Array.<module:model/Patent>} accomplishment_patents
 */
PersonEndpointResponse.prototype['accomplishment_patents'] = undefined;

/**
 * List of noteworthy courses partook by this user.
 * @member {Array.<module:model/Course>} accomplishment_courses
 */
PersonEndpointResponse.prototype['accomplishment_courses'] = undefined;

/**
 * List of noteworthy projects undertaken by this user.
 * @member {Array.<module:model/Project>} accomplishment_projects
 */
PersonEndpointResponse.prototype['accomplishment_projects'] = undefined;

/**
 * List of noteworthy test scores accomplished by this user.
 * @member {Array.<module:model/TestScore>} accomplishment_test_scores
 */
PersonEndpointResponse.prototype['accomplishment_test_scores'] = undefined;

/**
 * List of historic volunteer work experiences.
 * @member {Array.<module:model/VolunteeringExperience>} volunteer_work
 */
PersonEndpointResponse.prototype['volunteer_work'] = undefined;

/**
 * List of noteworthy certifications accomplished by this user.
 * @member {Array.<module:model/Certification>} certifications
 */
PersonEndpointResponse.prototype['certifications'] = undefined;

/**
 * Total *count* of LinkedIn connections.
 * @member {Number} connections
 */
PersonEndpointResponse.prototype['connections'] = undefined;

/**
 * A list of other LinkedIn profiles closely related to this user.
 * @member {Array.<module:model/PeopleAlsoViewed>} people_also_viewed
 */
PersonEndpointResponse.prototype['people_also_viewed'] = undefined;

/**
 * List of recommendations made by other users about this profile.
 * @member {Array.<String>} recommendations
 */
PersonEndpointResponse.prototype['recommendations'] = undefined;

/**
 * A list of LinkedIn status activities.
 * @member {Array.<module:model/Activity>} activities
 */
PersonEndpointResponse.prototype['activities'] = undefined;

/**
 * A list of other LinkedIn profiles with similar names.
 * @member {Array.<module:model/SimilarProfile>} similarly_named_profiles
 */
PersonEndpointResponse.prototype['similarly_named_profiles'] = undefined;

/**
 * A list of content-based articles posted by this user.
 * @member {Array.<module:model/Article>} articles
 */
PersonEndpointResponse.prototype['articles'] = undefined;

/**
 * A list of LinkedIn groups that this user is a part of.
 * @member {Array.<module:model/PersonGroup>} groups
 */
PersonEndpointResponse.prototype['groups'] = undefined;

/**
 * A list of keyword-based skills that this user boasts of on his LinkedIn profile.
 * @member {Array.<String>} skills
 */
PersonEndpointResponse.prototype['skills'] = undefined;

/**
 * @member {module:model/PersonEndpointResponseInferredSalary} inferred_salary
 */
PersonEndpointResponse.prototype['inferred_salary'] = undefined;

/**
 * Gender of the user.
 * @member {String} gender
 */
PersonEndpointResponse.prototype['gender'] = undefined;

/**
 * @member {module:model/PersonEndpointResponseBirthDate} birth_date
 */
PersonEndpointResponse.prototype['birth_date'] = undefined;

/**
 * Industry that the user works in.
 * @member {String} industry
 */
PersonEndpointResponse.prototype['industry'] = undefined;

/**
 * A list of interests that the user has.
 * @member {Array.<String>} interests
 */
PersonEndpointResponse.prototype['interests'] = undefined;

/**
 * @member {module:model/PersonEndpointResponseExtra} extra
 */
PersonEndpointResponse.prototype['extra'] = undefined;

/**
 * A list of personal emails associated with this user.
 * @member {Array.<String>} personal_emails
 */
PersonEndpointResponse.prototype['personal_emails'] = undefined;

/**
 * A list of personal mobile phone numbers associated with this user.
 * @member {Array.<String>} personal_numbers
 */
PersonEndpointResponse.prototype['personal_numbers'] = undefined;






export default PersonEndpointResponse;

