/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InferredSalary from './InferredSalary';

/**
 * The PersonEndpointResponseInferredSalary model module.
 * @module model/PersonEndpointResponseInferredSalary
 * @version 1.0.0
 */
class PersonEndpointResponseInferredSalary {
    /**
     * Constructs a new <code>PersonEndpointResponseInferredSalary</code>.
     * A salary range inferred from the user&#39;s current job title and company.
     * @alias module:model/PersonEndpointResponseInferredSalary
     * @implements module:model/InferredSalary
     */
    constructor() { 
        InferredSalary.initialize(this);
        PersonEndpointResponseInferredSalary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonEndpointResponseInferredSalary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonEndpointResponseInferredSalary} obj Optional instance to populate.
     * @return {module:model/PersonEndpointResponseInferredSalary} The populated <code>PersonEndpointResponseInferredSalary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonEndpointResponseInferredSalary();
            InferredSalary.constructFromObject(data, obj);

            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonEndpointResponseInferredSalary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonEndpointResponseInferredSalary</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} min
 */
PersonEndpointResponseInferredSalary.prototype['min'] = undefined;

/**
 * @member {Number} max
 */
PersonEndpointResponseInferredSalary.prototype['max'] = undefined;


// Implement InferredSalary interface:
/**
 * @member {Number} min
 */
InferredSalary.prototype['min'] = undefined;
/**
 * @member {Number} max
 */
InferredSalary.prototype['max'] = undefined;




export default PersonEndpointResponseInferredSalary;

