/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Person from './Person';

/**
 * The PersonSearchResult model module.
 * @module model/PersonSearchResult
 * @version 1.0.0
 */
class PersonSearchResult {
    /**
     * Constructs a new <code>PersonSearchResult</code>.
     * @alias module:model/PersonSearchResult
     */
    constructor() {

        PersonSearchResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>PersonSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonSearchResult} obj Optional instance to populate.
     * @return {module:model/PersonSearchResult} The populated <code>PersonSearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonSearchResult();

            if (data.hasOwnProperty('linkedin_profile_url')) {
                obj['linkedin_profile_url'] = ApiClient.convertToType(data['linkedin_profile_url'], 'String');
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], Person);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonSearchResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonSearchResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['linkedin_profile_url'] && !(typeof data['linkedin_profile_url'] === 'string' || data['linkedin_profile_url'] instanceof String)) {
            throw new Error("Expected the field `linkedin_profile_url` to be a primitive type in the JSON string but got " + data['linkedin_profile_url']);
        }
        if (data['profile']) { // data not null
            // validate the optional field `profile`
            Person.validateJsonObject(item);
        }

        return true;
    }


}

/**
 * The LinkedIn Profile URL of the person.             
 * @member {String} linkedin_profile_url
 */
PersonSearchResult.prototype['linkedin_profile_url'] = undefined;

/**
 * If `enrich_profiles=enrich` is specified, the person's entire profile is returned.
 * Otherwise this field will return `null`.             
 * @member {Person} profile
 */
PersonSearchResult.prototype['profile'] = undefined;

export default PersonSearchResult;

