/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonGroup model module.
 * @module model/PersonGroup
 * @version 1.0.0
 */
class PersonGroup {
    /**
     * Constructs a new <code>PersonGroup</code>.
     * @alias module:model/PersonGroup
     */
    constructor() { 
        
        PersonGroup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonGroup} obj Optional instance to populate.
     * @return {module:model/PersonGroup} The populated <code>PersonGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonGroup();

            if (data.hasOwnProperty('profile_pic_url')) {
                obj['profile_pic_url'] = ApiClient.convertToType(data['profile_pic_url'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonGroup</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['profile_pic_url'] && !(typeof data['profile_pic_url'] === 'string' || data['profile_pic_url'] instanceof String)) {
            throw new Error("Expected the field `profile_pic_url` to be a primitive type in the JSON string but got " + data['profile_pic_url']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
 * The URL to the profile picture of this LinkedIn Group
 * @member {String} profile_pic_url
 */
PersonGroup.prototype['profile_pic_url'] = undefined;

/**
 * Name of LinkedIn group for which this user is in
 * @member {String} name
 */
PersonGroup.prototype['name'] = undefined;

/**
 * URL to the LinkedIn Group
 * @member {String} url
 */
PersonGroup.prototype['url'] = undefined;






export default PersonGroup;

