/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProfilePicture model module.
 * @module model/ProfilePicture
 * @version 1.0.0
 */
class ProfilePicture {
    /**
     * Constructs a new <code>ProfilePicture</code>.
     * @alias module:model/ProfilePicture
     */
    constructor() { 
        
        ProfilePicture.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProfilePicture</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProfilePicture} obj Optional instance to populate.
     * @return {module:model/ProfilePicture} The populated <code>ProfilePicture</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProfilePicture();

            if (data.hasOwnProperty('tmp_profile_pic_url')) {
                obj['tmp_profile_pic_url'] = ApiClient.convertToType(data['tmp_profile_pic_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProfilePicture</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProfilePicture</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tmp_profile_pic_url'] && !(typeof data['tmp_profile_pic_url'] === 'string' || data['tmp_profile_pic_url'] instanceof String)) {
            throw new Error("Expected the field `tmp_profile_pic_url` to be a primitive type in the JSON string but got " + data['tmp_profile_pic_url']);
        }

        return true;
    }


}



/**
 *              Temporary URL to the profile picture (valid for just 30 minutes).             See this [blog post](https://nubela.co/blog/why-is-the-api-returning-s3-links-for-profile-pictures-scraped-from-linkedin-profiles/) for more information.
 * @member {String} tmp_profile_pic_url
 */
ProfilePicture.prototype['tmp_profile_pic_url'] = undefined;






export default ProfilePicture;

