/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RoleSearchResult model module.
 * @module model/RoleSearchResult
 * @version 1.0.0
 */
class RoleSearchResult {
    /**
     * Constructs a new <code>RoleSearchResult</code>.
     * @alias module:model/RoleSearchResult
     */
    constructor() { 
        
        RoleSearchResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RoleSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleSearchResult} obj Optional instance to populate.
     * @return {module:model/RoleSearchResult} The populated <code>RoleSearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleSearchResult();

            if (data.hasOwnProperty('linkedin_profile_url')) {
                obj['linkedin_profile_url'] = ApiClient.convertToType(data['linkedin_profile_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RoleSearchResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RoleSearchResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['linkedin_profile_url'] && !(typeof data['linkedin_profile_url'] === 'string' || data['linkedin_profile_url'] instanceof String)) {
            throw new Error("Expected the field `linkedin_profile_url` to be a primitive type in the JSON string but got " + data['linkedin_profile_url']);
        }

        return true;
    }


}



/**
 * LinkedIn Profile URL of the person that most closely matches the role
 * @member {String} linkedin_profile_url
 */
RoleSearchResult.prototype['linkedin_profile_url'] = undefined;






export default RoleSearchResult;

