/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import JobListPage from '../model/JobListPage';
import LinkedinJob from '../model/LinkedinJob';

/**
* JobsAPI service.
* @module api/JobsAPIApi
* @version 1.0.0
*/
export default class JobsAPIApi {

    /**
    * Constructs a new JobsAPIApi. 
    * @alias module:api/JobsAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the jobProfileEndpoint operation.
     * @callback module:api/JobsAPIApi~jobProfileEndpointCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LinkedinJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cost: 2 credits / successful request. Get structured data of a LinkedIn Job Profile
     * @param {String} url      URL of the LinkedIn Job Profile to target.      URL should be in the format of     `https://www.linkedin.com/jobs/view/<job_id>`.     [Jobs Listing Endpoint](#jobs-api-jobs-listing-endpoint)     can be used to retrieve a job URL.     
     * @param {module:api/JobsAPIApi~jobProfileEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LinkedinJob}
     */
    jobProfileEndpoint(url, callback) {
      let postBody = null;
      // verify the required parameter 'url' is set
      if (url === undefined || url === null) {
        throw new Error("Missing the required parameter 'url' when calling jobProfileEndpoint");
      }

      let pathParams = {
      };
      let queryParams = {
        'url': url
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LinkedinJob;
      return this.apiClient.callApi(
        '/api/linkedin/job', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the jobsListingEndpoint operation.
     * @callback module:api/JobsAPIApi~jobsListingEndpointCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JobListPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cost: 2 credits / successful request. List jobs posted by a company on LinkedIn
     * @param {String} searchId      The `search_id` of the company on LinkedIn.     You can get the `search_id` of a LinkedIn company via     [Company Profile API](#company-api-company-profile-endpoint).     
     * @param {module:api/JobsAPIApi~jobsListingEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JobListPage}
     */
    jobsListingEndpoint(searchId, callback) {
      let postBody = null;
      // verify the required parameter 'searchId' is set
      if (searchId === undefined || searchId === null) {
        throw new Error("Missing the required parameter 'searchId' when calling jobsListingEndpoint");
      }

      let pathParams = {
      };
      let queryParams = {
        'search_id': searchId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = JobListPage;
      return this.apiClient.callApi(
        '/api/v2/linkedin/company/job', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
