/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreditBalance from '../model/CreditBalance';

/**
* MetaAPI service.
* @module api/MetaAPIApi
* @version 1.0.0
*/
export default class MetaAPIApi {

    /**
    * Constructs a new MetaAPIApi. 
    * @alias module:api/MetaAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the viewCreditBalanceEndpoint operation.
     * @callback module:api/MetaAPIApi~viewCreditBalanceEndpointCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreditBalance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cost: 0 credit / successful request. Get your current credit(s) balance
     * @param {module:api/MetaAPIApi~viewCreditBalanceEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreditBalance}
     */
    viewCreditBalanceEndpoint(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreditBalance;
      return this.apiClient.callApi(
        '/api/credit-balance', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
