/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompanyReveal from '../model/CompanyReveal';

/**
* RevealAPI service.
* @module api/RevealAPIApi
* @version 1.0.0
*/
export default class RevealAPIApi {

    /**
    * Constructs a new RevealAPIApi. 
    * @alias module:api/RevealAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the revealEndpoint operation.
     * @callback module:api/RevealAPIApi~revealEndpointCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompanyReveal} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cost: 2 credits / successful request. Deanonymize an IPv4 address and associate the Company behind the IPv4 address.
     * @param {String} ip      The target IPv4 address.     
     * @param {Object} opts Optional parameters
     * @param {String} opts.roleContactNumber      Append personal contact numbers to the response if the system finds a relevant person profile.     
     * @param {String} opts.rolePersonalEmail      Append personal email addresses to the response if the system finds a relevant person profile.     
     * @param {String} opts.role      Lookup and append an employee of a certain role of the company.     Within the same API call, You can choose to lookup a person with a given role within this organisation that you might want to reach out to.     
     * @param {module:api/RevealAPIApi~revealEndpointCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompanyReveal}
     */
    revealEndpoint(ip, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'ip' is set
      if (ip === undefined || ip === null) {
        throw new Error("Missing the required parameter 'ip' when calling revealEndpoint");
      }

      let pathParams = {
      };
      let queryParams = {
        'role_contact_number': opts['roleContactNumber'],
        'role_personal_email': opts['rolePersonalEmail'],
        'role': opts['role'],
        'ip': ip
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CompanyReveal;
      return this.apiClient.callApi(
        '/api/reveal/company', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
