/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxycurlApi);
  }
}(this, function(expect, ProxycurlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxycurlApi.CompanyDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyDetails', function() {
    it('should create an instance of CompanyDetails', function() {
      // uncomment below and update the code to test CompanyDetails
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be.a(ProxycurlApi.CompanyDetails);
    });

    it('should have the property ipoStatus (base name: "ipo_status")', function() {
      // uncomment below and update the code to test the property ipoStatus
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property crunchbaseRank (base name: "crunchbase_rank")', function() {
      // uncomment below and update the code to test the property crunchbaseRank
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property foundingDate (base name: "founding_date")', function() {
      // uncomment below and update the code to test the property foundingDate
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property operatingStatus (base name: "operating_status")', function() {
      // uncomment below and update the code to test the property operatingStatus
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "company_type")', function() {
      // uncomment below and update the code to test the property companyType
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property contactEmail (base name: "contact_email")', function() {
      // uncomment below and update the code to test the property contactEmail
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phone_number")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property facebookId (base name: "facebook_id")', function() {
      // uncomment below and update the code to test the property facebookId
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property twitterId (base name: "twitter_id")', function() {
      // uncomment below and update the code to test the property twitterId
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfFundingRounds (base name: "number_of_funding_rounds")', function() {
      // uncomment below and update the code to test the property numberOfFundingRounds
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property totalFundingAmount (base name: "total_funding_amount")', function() {
      // uncomment below and update the code to test the property totalFundingAmount
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property stockSymbol (base name: "stock_symbol")', function() {
      // uncomment below and update the code to test the property stockSymbol
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property ipoDate (base name: "ipo_date")', function() {
      // uncomment below and update the code to test the property ipoDate
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfLeadInvestors (base name: "number_of_lead_investors")', function() {
      // uncomment below and update the code to test the property numberOfLeadInvestors
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfInvestors (base name: "number_of_investors")', function() {
      // uncomment below and update the code to test the property numberOfInvestors
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property totalFundRaised (base name: "total_fund_raised")', function() {
      // uncomment below and update the code to test the property totalFundRaised
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfInvestments (base name: "number_of_investments")', function() {
      // uncomment below and update the code to test the property numberOfInvestments
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfLeadInvestments (base name: "number_of_lead_investments")', function() {
      // uncomment below and update the code to test the property numberOfLeadInvestments
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfExits (base name: "number_of_exits")', function() {
      // uncomment below and update the code to test the property numberOfExits
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

    it('should have the property numberOfAcquisitions (base name: "number_of_acquisitions")', function() {
      // uncomment below and update the code to test the property numberOfAcquisitions
      //var instance = new ProxycurlApi.CompanyDetails();
      //expect(instance).to.be();
    });

  });

}));
