/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxycurlApi);
  }
}(this, function(expect, ProxycurlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxycurlApi.Education();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Education', function() {
    it('should create an instance of Education', function() {
      // uncomment below and update the code to test Education
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be.a(ProxycurlApi.Education);
    });

    it('should have the property startsAt (base name: "starts_at")', function() {
      // uncomment below and update the code to test the property startsAt
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property endsAt (base name: "ends_at")', function() {
      // uncomment below and update the code to test the property endsAt
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property fieldOfStudy (base name: "field_of_study")', function() {
      // uncomment below and update the code to test the property fieldOfStudy
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property degreeName (base name: "degree_name")', function() {
      // uncomment below and update the code to test the property degreeName
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property school (base name: "school")', function() {
      // uncomment below and update the code to test the property school
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property schoolLinkedinProfileUrl (base name: "school_linkedin_profile_url")', function() {
      // uncomment below and update the code to test the property schoolLinkedinProfileUrl
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

    it('should have the property logoUrl (base name: "logo_url")', function() {
      // uncomment below and update the code to test the property logoUrl
      //var instance = new ProxycurlApi.Education();
      //expect(instance).to.be();
    });

  });

}));
