/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxycurlApi);
  }
}(this, function(expect, ProxycurlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxycurlApi.LinkedinJob();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LinkedinJob', function() {
    it('should create an instance of LinkedinJob', function() {
      // uncomment below and update the code to test LinkedinJob
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be.a(ProxycurlApi.LinkedinJob);
    });

    it('should have the property linkedinInternalId (base name: "linkedin_internal_id")', function() {
      // uncomment below and update the code to test the property linkedinInternalId
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property jobDescription (base name: "job_description")', function() {
      // uncomment below and update the code to test the property jobDescription
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property applyUrl (base name: "apply_url")', function() {
      // uncomment below and update the code to test the property applyUrl
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property seniorityLevel (base name: "seniority_level")', function() {
      // uncomment below and update the code to test the property seniorityLevel
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property industry (base name: "industry")', function() {
      // uncomment below and update the code to test the property industry
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property employmentType (base name: "employment_type")', function() {
      // uncomment below and update the code to test the property employmentType
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property jobFunctions (base name: "job_functions")', function() {
      // uncomment below and update the code to test the property jobFunctions
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

    it('should have the property totalApplicants (base name: "total_applicants")', function() {
      // uncomment below and update the code to test the property totalApplicants
      //var instance = new ProxycurlApi.LinkedinJob();
      //expect(instance).to.be();
    });

  });

}));
