/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxycurlApi);
  }
}(this, function(expect, ProxycurlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxycurlApi.LinkedinSchool();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LinkedinSchool', function() {
    it('should create an instance of LinkedinSchool', function() {
      // uncomment below and update the code to test LinkedinSchool
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be.a(ProxycurlApi.LinkedinSchool);
    });

    it('should have the property linkedinInternalId (base name: "linkedin_internal_id")', function() {
      // uncomment below and update the code to test the property linkedinInternalId
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property industry (base name: "industry")', function() {
      // uncomment below and update the code to test the property industry
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property companySize (base name: "company_size")', function() {
      // uncomment below and update the code to test the property companySize
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property companySizeOnLinkedin (base name: "company_size_on_linkedin")', function() {
      // uncomment below and update the code to test the property companySizeOnLinkedin
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property hq (base name: "hq")', function() {
      // uncomment below and update the code to test the property hq
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "company_type")', function() {
      // uncomment below and update the code to test the property companyType
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property foundedYear (base name: "founded_year")', function() {
      // uncomment below and update the code to test the property foundedYear
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property specialities (base name: "specialities")', function() {
      // uncomment below and update the code to test the property specialities
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property locations (base name: "locations")', function() {
      // uncomment below and update the code to test the property locations
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property tagline (base name: "tagline")', function() {
      // uncomment below and update the code to test the property tagline
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property universalNameId (base name: "universal_name_id")', function() {
      // uncomment below and update the code to test the property universalNameId
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property profilePicUrl (base name: "profile_pic_url")', function() {
      // uncomment below and update the code to test the property profilePicUrl
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property backgroundCoverImageUrl (base name: "background_cover_image_url")', function() {
      // uncomment below and update the code to test the property backgroundCoverImageUrl
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property searchId (base name: "search_id")', function() {
      // uncomment below and update the code to test the property searchId
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property similarCompanies (base name: "similar_companies")', function() {
      // uncomment below and update the code to test the property similarCompanies
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property updates (base name: "updates")', function() {
      // uncomment below and update the code to test the property updates
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

    it('should have the property followerCount (base name: "follower_count")', function() {
      // uncomment below and update the code to test the property followerCount
      //var instance = new ProxycurlApi.LinkedinSchool();
      //expect(instance).to.be();
    });

  });

}));
