/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxycurlApi);
  }
}(this, function(expect, ProxycurlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxycurlApi.Patent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Patent', function() {
    it('should create an instance of Patent', function() {
      // uncomment below and update the code to test Patent
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be.a(ProxycurlApi.Patent);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

    it('should have the property issuer (base name: "issuer")', function() {
      // uncomment below and update the code to test the property issuer
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

    it('should have the property issuedOn (base name: "issued_on")', function() {
      // uncomment below and update the code to test the property issuedOn
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

    it('should have the property applicationNumber (base name: "application_number")', function() {
      // uncomment below and update the code to test the property applicationNumber
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

    it('should have the property patentNumber (base name: "patent_number")', function() {
      // uncomment below and update the code to test the property patentNumber
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new ProxycurlApi.Patent();
      //expect(instance).to.be();
    });

  });

}));
