/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccomplishmentOrg from './model/AccomplishmentOrg';
import AcquiredCompany from './model/AcquiredCompany';
import AcquiredCompanyAnnouncedDate from './model/AcquiredCompanyAnnouncedDate';
import Acquisition from './model/Acquisition';
import AcquisitionAcquiredBy from './model/AcquisitionAcquiredBy';
import Acquisitor from './model/Acquisitor';
import Activity from './model/Activity';
import Article from './model/Article';
import Certification from './model/Certification';
import CompanyDetails from './model/CompanyDetails';
import CompanyDetailsFoundingDate from './model/CompanyDetailsFoundingDate';
import CompanyDetailsIpoDate from './model/CompanyDetailsIpoDate';
import CompanyLocation from './model/CompanyLocation';
import CompanyReveal from './model/CompanyReveal';
import CompanyRevealCompany from './model/CompanyRevealCompany';
import CompanyRevealRoleProfile from './model/CompanyRevealRoleProfile';
import CompanyUpdate from './model/CompanyUpdate';
import CompanyUpdatePostedOn from './model/CompanyUpdatePostedOn';
import Course from './model/Course';
import CreditBalance from './model/CreditBalance';
import DisposableEmail from './model/DisposableEmail';
import Education from './model/Education';
import Employee from './model/Employee';
import EmployeeCount from './model/EmployeeCount';
import EmployeeList from './model/EmployeeList';
import EmployeeProfile from './model/EmployeeProfile';
import Exit from './model/Exit';
import Experience from './model/Experience';
import ExtractionEmailResult from './model/ExtractionEmailResult';
import Funding from './model/Funding';
import FundingAnnouncedDate from './model/FundingAnnouncedDate';
import HonourAward from './model/HonourAward';
import HonourAwardIssuedOn from './model/HonourAwardIssuedOn';
import InferredSalary from './model/InferredSalary';
import Investor from './model/Investor';
import Job from './model/Job';
import JobCompany from './model/JobCompany';
import JobListPage from './model/JobListPage';
import JobLocation from './model/JobLocation';
import LinkedinCompany from './model/LinkedinCompany';
import LinkedinCompanyAcquisitions from './model/LinkedinCompanyAcquisitions';
import LinkedinCompanyExtra from './model/LinkedinCompanyExtra';
import LinkedinCompanyHq from './model/LinkedinCompanyHq';
import LinkedinJob from './model/LinkedinJob';
import LinkedinJobCompany from './model/LinkedinJobCompany';
import LinkedinJobLocation from './model/LinkedinJobLocation';
import LinkedinSchool from './model/LinkedinSchool';
import ModelDate from './model/ModelDate';
import PDLEmailResult from './model/PDLEmailResult';
import PDLPhoneNumberResult from './model/PDLPhoneNumberResult';
import Patent from './model/Patent';
import PatentIssuedOn from './model/PatentIssuedOn';
import PeopleAlsoViewed from './model/PeopleAlsoViewed';
import Person from './model/Person';
import PersonEndpointResponse from './model/PersonEndpointResponse';
import PersonEndpointResponseBirthDate from './model/PersonEndpointResponseBirthDate';
import PersonEndpointResponseExtra from './model/PersonEndpointResponseExtra';
import PersonEndpointResponseInferredSalary from './model/PersonEndpointResponseInferredSalary';
import PersonExtra from './model/PersonExtra';
import PersonGroup from './model/PersonGroup';
import ProfilePicture from './model/ProfilePicture';
import Project from './model/Project';
import Publication from './model/Publication';
import PublicationPublishedOn from './model/PublicationPublishedOn';
import RoleSearchResult from './model/RoleSearchResult';
import SimilarCompany from './model/SimilarCompany';
import SimilarProfile from './model/SimilarProfile';
import TestScore from './model/TestScore';
import TestScoreDateOn from './model/TestScoreDateOn';
import UrlResult from './model/UrlResult';
import UrlResult1 from './model/UrlResult1';
import UrlResult2 from './model/UrlResult2';
import VolunteeringExperience from './model/VolunteeringExperience';
import CompanyAPIApi from './api/CompanyAPIApi';
import ContactAPIApi from './api/ContactAPIApi';
import JobsAPIApi from './api/JobsAPIApi';
import MetaAPIApi from './api/MetaAPIApi';
import PeopleAPIApi from './api/PeopleAPIApi';
import RevealAPIApi from './api/RevealAPIApi';
import SchoolAPIApi from './api/SchoolAPIApi';
import SearchAPIApi from './api/SearchAPIApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProxycurlApi = require('index'); // See note below*.
* var xxxSvc = new ProxycurlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProxycurlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProxycurlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProxycurlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccomplishmentOrg model constructor.
     * @property {module:model/AccomplishmentOrg}
     */
    AccomplishmentOrg,

    /**
     * The AcquiredCompany model constructor.
     * @property {module:model/AcquiredCompany}
     */
    AcquiredCompany,

    /**
     * The AcquiredCompanyAnnouncedDate model constructor.
     * @property {module:model/AcquiredCompanyAnnouncedDate}
     */
    AcquiredCompanyAnnouncedDate,

    /**
     * The Acquisition model constructor.
     * @property {module:model/Acquisition}
     */
    Acquisition,

    /**
     * The AcquisitionAcquiredBy model constructor.
     * @property {module:model/AcquisitionAcquiredBy}
     */
    AcquisitionAcquiredBy,

    /**
     * The Acquisitor model constructor.
     * @property {module:model/Acquisitor}
     */
    Acquisitor,

    /**
     * The Activity model constructor.
     * @property {module:model/Activity}
     */
    Activity,

    /**
     * The Article model constructor.
     * @property {module:model/Article}
     */
    Article,

    /**
     * The Certification model constructor.
     * @property {module:model/Certification}
     */
    Certification,

    /**
     * The CompanyDetails model constructor.
     * @property {module:model/CompanyDetails}
     */
    CompanyDetails,

    /**
     * The CompanyDetailsFoundingDate model constructor.
     * @property {module:model/CompanyDetailsFoundingDate}
     */
    CompanyDetailsFoundingDate,

    /**
     * The CompanyDetailsIpoDate model constructor.
     * @property {module:model/CompanyDetailsIpoDate}
     */
    CompanyDetailsIpoDate,

    /**
     * The CompanyLocation model constructor.
     * @property {module:model/CompanyLocation}
     */
    CompanyLocation,

    /**
     * The CompanyReveal model constructor.
     * @property {module:model/CompanyReveal}
     */
    CompanyReveal,

    /**
     * The CompanyRevealCompany model constructor.
     * @property {module:model/CompanyRevealCompany}
     */
    CompanyRevealCompany,

    /**
     * The CompanyRevealRoleProfile model constructor.
     * @property {module:model/CompanyRevealRoleProfile}
     */
    CompanyRevealRoleProfile,

    /**
     * The CompanyUpdate model constructor.
     * @property {module:model/CompanyUpdate}
     */
    CompanyUpdate,

    /**
     * The CompanyUpdatePostedOn model constructor.
     * @property {module:model/CompanyUpdatePostedOn}
     */
    CompanyUpdatePostedOn,

    /**
     * The Course model constructor.
     * @property {module:model/Course}
     */
    Course,

    /**
     * The CreditBalance model constructor.
     * @property {module:model/CreditBalance}
     */
    CreditBalance,

    /**
     * The DisposableEmail model constructor.
     * @property {module:model/DisposableEmail}
     */
    DisposableEmail,

    /**
     * The Education model constructor.
     * @property {module:model/Education}
     */
    Education,

    /**
     * The Employee model constructor.
     * @property {module:model/Employee}
     */
    Employee,

    /**
     * The EmployeeCount model constructor.
     * @property {module:model/EmployeeCount}
     */
    EmployeeCount,

    /**
     * The EmployeeList model constructor.
     * @property {module:model/EmployeeList}
     */
    EmployeeList,

    /**
     * The EmployeeProfile model constructor.
     * @property {module:model/EmployeeProfile}
     */
    EmployeeProfile,

    /**
     * The Exit model constructor.
     * @property {module:model/Exit}
     */
    Exit,

    /**
     * The Experience model constructor.
     * @property {module:model/Experience}
     */
    Experience,

    /**
     * The ExtractionEmailResult model constructor.
     * @property {module:model/ExtractionEmailResult}
     */
    ExtractionEmailResult,

    /**
     * The Funding model constructor.
     * @property {module:model/Funding}
     */
    Funding,

    /**
     * The FundingAnnouncedDate model constructor.
     * @property {module:model/FundingAnnouncedDate}
     */
    FundingAnnouncedDate,

    /**
     * The HonourAward model constructor.
     * @property {module:model/HonourAward}
     */
    HonourAward,

    /**
     * The HonourAwardIssuedOn model constructor.
     * @property {module:model/HonourAwardIssuedOn}
     */
    HonourAwardIssuedOn,

    /**
     * The InferredSalary model constructor.
     * @property {module:model/InferredSalary}
     */
    InferredSalary,

    /**
     * The Investor model constructor.
     * @property {module:model/Investor}
     */
    Investor,

    /**
     * The Job model constructor.
     * @property {module:model/Job}
     */
    Job,

    /**
     * The JobCompany model constructor.
     * @property {module:model/JobCompany}
     */
    JobCompany,

    /**
     * The JobListPage model constructor.
     * @property {module:model/JobListPage}
     */
    JobListPage,

    /**
     * The JobLocation model constructor.
     * @property {module:model/JobLocation}
     */
    JobLocation,

    /**
     * The LinkedinCompany model constructor.
     * @property {module:model/LinkedinCompany}
     */
    LinkedinCompany,

    /**
     * The LinkedinCompanyAcquisitions model constructor.
     * @property {module:model/LinkedinCompanyAcquisitions}
     */
    LinkedinCompanyAcquisitions,

    /**
     * The LinkedinCompanyExtra model constructor.
     * @property {module:model/LinkedinCompanyExtra}
     */
    LinkedinCompanyExtra,

    /**
     * The LinkedinCompanyHq model constructor.
     * @property {module:model/LinkedinCompanyHq}
     */
    LinkedinCompanyHq,

    /**
     * The LinkedinJob model constructor.
     * @property {module:model/LinkedinJob}
     */
    LinkedinJob,

    /**
     * The LinkedinJobCompany model constructor.
     * @property {module:model/LinkedinJobCompany}
     */
    LinkedinJobCompany,

    /**
     * The LinkedinJobLocation model constructor.
     * @property {module:model/LinkedinJobLocation}
     */
    LinkedinJobLocation,

    /**
     * The LinkedinSchool model constructor.
     * @property {module:model/LinkedinSchool}
     */
    LinkedinSchool,

    /**
     * The ModelDate model constructor.
     * @property {module:model/ModelDate}
     */
    ModelDate,

    /**
     * The PDLEmailResult model constructor.
     * @property {module:model/PDLEmailResult}
     */
    PDLEmailResult,

    /**
     * The PDLPhoneNumberResult model constructor.
     * @property {module:model/PDLPhoneNumberResult}
     */
    PDLPhoneNumberResult,

    /**
     * The Patent model constructor.
     * @property {module:model/Patent}
     */
    Patent,

    /**
     * The PatentIssuedOn model constructor.
     * @property {module:model/PatentIssuedOn}
     */
    PatentIssuedOn,

    /**
     * The PeopleAlsoViewed model constructor.
     * @property {module:model/PeopleAlsoViewed}
     */
    PeopleAlsoViewed,

    /**
     * The Person model constructor.
     * @property {module:model/Person}
     */
    Person,

    /**
     * The PersonEndpointResponse model constructor.
     * @property {module:model/PersonEndpointResponse}
     */
    PersonEndpointResponse,

    /**
     * The PersonEndpointResponseBirthDate model constructor.
     * @property {module:model/PersonEndpointResponseBirthDate}
     */
    PersonEndpointResponseBirthDate,

    /**
     * The PersonEndpointResponseExtra model constructor.
     * @property {module:model/PersonEndpointResponseExtra}
     */
    PersonEndpointResponseExtra,

    /**
     * The PersonEndpointResponseInferredSalary model constructor.
     * @property {module:model/PersonEndpointResponseInferredSalary}
     */
    PersonEndpointResponseInferredSalary,

    /**
     * The PersonExtra model constructor.
     * @property {module:model/PersonExtra}
     */
    PersonExtra,

    /**
     * The PersonGroup model constructor.
     * @property {module:model/PersonGroup}
     */
    PersonGroup,

    /**
     * The ProfilePicture model constructor.
     * @property {module:model/ProfilePicture}
     */
    ProfilePicture,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The Publication model constructor.
     * @property {module:model/Publication}
     */
    Publication,

    /**
     * The PublicationPublishedOn model constructor.
     * @property {module:model/PublicationPublishedOn}
     */
    PublicationPublishedOn,

    /**
     * The RoleSearchResult model constructor.
     * @property {module:model/RoleSearchResult}
     */
    RoleSearchResult,

    /**
     * The SimilarCompany model constructor.
     * @property {module:model/SimilarCompany}
     */
    SimilarCompany,

    /**
     * The SimilarProfile model constructor.
     * @property {module:model/SimilarProfile}
     */
    SimilarProfile,

    /**
     * The TestScore model constructor.
     * @property {module:model/TestScore}
     */
    TestScore,

    /**
     * The TestScoreDateOn model constructor.
     * @property {module:model/TestScoreDateOn}
     */
    TestScoreDateOn,

    /**
     * The UrlResult model constructor.
     * @property {module:model/UrlResult}
     */
    UrlResult,

    /**
     * The UrlResult1 model constructor.
     * @property {module:model/UrlResult1}
     */
    UrlResult1,

    /**
     * The UrlResult2 model constructor.
     * @property {module:model/UrlResult2}
     */
    UrlResult2,

    /**
     * The VolunteeringExperience model constructor.
     * @property {module:model/VolunteeringExperience}
     */
    VolunteeringExperience,

    /**
    * The CompanyAPIApi service constructor.
    * @property {module:api/CompanyAPIApi}
    */
    CompanyAPIApi,

    /**
    * The ContactAPIApi service constructor.
    * @property {module:api/ContactAPIApi}
    */
    ContactAPIApi,

    /**
    * The JobsAPIApi service constructor.
    * @property {module:api/JobsAPIApi}
    */
    JobsAPIApi,

    /**
    * The MetaAPIApi service constructor.
    * @property {module:api/MetaAPIApi}
    */
    MetaAPIApi,

    /**
    * The PeopleAPIApi service constructor.
    * @property {module:api/PeopleAPIApi}
    */
    PeopleAPIApi,

    /**
    * The RevealAPIApi service constructor.
    * @property {module:api/RevealAPIApi}
    */
    RevealAPIApi,

    /**
    * The SchoolAPIApi service constructor.
    * @property {module:api/SchoolAPIApi}
    */
    SchoolAPIApi,

    /**
    * The SearchAPIApi service constructor.
    * @property {module:api/SearchAPIApi}
    */
    SearchAPIApi
};
