/**
 * Proxycurl API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxycurlApi);
  }
}(this, function(expect, ProxycurlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxycurlApi.ContactAPIApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactAPIApi', function() {
    describe('disposableEmailAddressCheckEndpoint', function() {
      it('should call disposableEmailAddressCheckEndpoint successfully', function(done) {
        //uncomment below and update the code to test disposableEmailAddressCheckEndpoint
        //instance.disposableEmailAddressCheckEndpoint(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('personalContactNumberLookupEndpoint', function() {
      it('should call personalContactNumberLookupEndpoint successfully', function(done) {
        //uncomment below and update the code to test personalContactNumberLookupEndpoint
        //instance.personalContactNumberLookupEndpoint(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('personalEmailLookupEndpoint', function() {
      it('should call personalEmailLookupEndpoint successfully', function(done) {
        //uncomment below and update the code to test personalEmailLookupEndpoint
        //instance.personalEmailLookupEndpoint(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reverseWorkEmailLookupEndpoint', function() {
      it('should call reverseWorkEmailLookupEndpoint successfully', function(done) {
        //uncomment below and update the code to test reverseWorkEmailLookupEndpoint
        //instance.reverseWorkEmailLookupEndpoint(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workEmailLookupEndpoint', function() {
      it('should call workEmailLookupEndpoint successfully', function(done) {
        //uncomment below and update the code to test workEmailLookupEndpoint
        //instance.workEmailLookupEndpoint(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
